### ISSUE TITLE
These properties are not written as public

### ISSUE THREAD

**Issue by Mx-Iris** [ChimeHQ/KeyCodes#1]
<img width="745" alt="image" src="https://github.com/ChimeHQ/KeyCodes/assets/61279231/f812d0d4-f8c8-4606-a9fc-c0cb679bea56">

**Comment by mattmassicotte** [comment]
Wow good catch. These also should be `let`. Thank you so much for the report. Fixed with https://github.com/ChimeHQ/KeyCodes/commit/e8360b7330823b7889efb7b0fe8bbb99db05cdfc
